### ISSUE TITLE
 Error inflating class CheckedTextView : Can't find ColorStateList from drawable resource

### ISSUE THREAD

**Issue by valmeeki001** [garretyoder/app-theme-engine#6]
Got this exception while inflating `CheckedTextView`. 

```
After processing ATECheckedTextView: tint|accent_color

 --------- beginning of crash
 FATAL EXCEPTION: main
                                                        Process: com.chat, PID: 9077
                                                        android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class CheckedTextView
                                                        Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class CheckedTextView
                                                        Caused by: java.lang.RuntimeException: Failed to run com.afollestad.appthemeengine.tagprocessors.TintTagProcessor: Can't find ColorStateList from drawable resource ID #0x7f020011
                                                            at com.afollestad.appthemeengine.viewprocessors.DefaultProcessor.processTagPart(DefaultProcessor.java:44)
                                                            at com.afollestad.appthemeengine.viewprocessors.DefaultProcessor.process(DefaultProcessor.java:26)
                                                            at com.afollestad.appthemeengine.viewprocessors.DefaultProcessor.process(DefaultProcessor.java:14)
                                                            at com.afollestad.appthemeengine.ATE.performDefaultProcessing(ATE.java:62)
                                                            at com.afollestad.appthemeengine.ATE.themeView(ATE.java:175)
                                                            at com.afollestad.appthemeengine.inflation.ATEViewUtil.init(ATEViewUtil.java:23)
                                                            at com.afollestad.appthemeengine.inflation.ATECheckedTextView.init(ATECheckedTextView.java:34)
                                                            at com.afollestad.appthemeengine.inflation.ATECheckedTextView.<init>(ATECheckedTextView.java:29)
                                                            at com.afollestad.appthemeengine.inflation.InflationInterceptor.onCreateView(InflationInterceptor.java:208)
                                                            at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                            at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:380)
                                                            at android.widget.ArrayAdapter.getView(ArrayAdapter.java:371)
                                                            at android.widget.AbsListView.obtainView(AbsListView.java:2360)
                                                            at android.widget.ListView.measureHeightOfChildren(ListView.java:1326)
                                                            at android.widget.ListView.onMeasure(ListView.java:1233)
                                                            at android.view.View.measure(View.java:19730)
                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                            at android.view.View.measure(View.java:19730)
                                                            at android.support.v7.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:135)
                                                            at android.support.v7.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:63)
                                                            at android.view.View.measure(View.java:19730)
                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                            at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                            at android.view.View.measure(View.java:19730)
                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                            at android.view.View.measure(View.java:19730)
                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                            at android.view.View.measure(View.java:19730)
                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                            at android.view.View.measure(View.java:19730)
                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                            at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
                                                            at android.view.View.measure(View.java:19730)
                                                            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
                                                            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1331)
                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
Caused by: android.content.res.Resources$NotFoundException: Can't find ColorStateList from drawable resource ID #0x7f020011
                                                            at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:840)
                                                            at android.content.res.Resources.loadColorStateList(Resources.java:998)
                                                            at android.content.res.TypedArray.getColor(TypedArray.java:451)
                                                            at com.afollestad.appthemeengine.util.ATEUtil.resolveColor(ATEUtil.java:67)
                                                            at com.afollestad.appthemeengine.util.ATEUtil.resolveColor(ATEUtil.java:61)
                                                            at com.afollestad.appthemeengine.tagprocessors.TagProcessor$ColorResult.isDark(TagProcessor.java:51)
                                                            at com.afollestad.appthemeengine.tagprocessors.TintTagProcessor.process(TintTagProcessor.java:65)
                                                            at com.afollestad.appthemeengine.viewprocessors.DefaultProcessor.processTagPart(DefaultProcessor.java:42)
                                                            	... 60 more
```

**Comment by nshul12** [comment]
is there a workaround for this ?

**Comment by garretyoder** [comment]
afollestad, app-theme-engine's developer took the repo down for the project when he discontinued it. Many apps still depend on it, so I kept my fork up as a mirror. However, I recommend using my own Colorful library as a better alternative that is not out of support. https://github.com/garretyoder/Colorful
