### ISSUE TITLE
App crashed (only signed apk) getting error: mItemData not found 

### ISSUE THREAD

**Issue by hirenmk** [garretyoder/app-theme-engine#7]
```
If i add     
<item
            android:id="@+id/search"
            android:icon="@drawable/ic_menu_search"
            android:title="@string/search_title"
            android:orderInCategory="1"
            app:showAsAction="ifRoom"
            />
this in menu file then app crashes otherwise it is working fine.


12-28 15:11:59.882 24053-24053/nu.com.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: nu.com.example, PID: 24053
                                                                          java.lang.RuntimeException: Failed to get ActionView from an ActionMenuItemView: No field mItemData in class Landroid/support/v7/view/menu/ActionMenuItemView; (declaration of 'android.support.v7.view.menu.ActionMenuItemView' appears in /data/app/nu.com.example-1/base.apk)
                                                                              at com.afollestad.appthemeengine.inflation.a.i(Unknown Source)
                                                                              at com.afollestad.appthemeengine.inflation.a.h(Unknown Source)
                                                                              at com.afollestad.appthemeengine.inflation.a.setIcon(Unknown Source)
                                                                              at android.support.v7.view.menu.ActionMenuItemView.a(Unknown Source)
                                                                              at android.support.v7.widget.d.a(Unknown Source)
                                                                              at android.support.v7.view.menu.b.a(Unknown Source)
                                                                              at android.support.v7.widget.d.a(Unknown Source)
                                                                              at android.support.v7.widget.d.a(Unknown Source)
                                                                              at android.support.v7.view.menu.h.j(Unknown Source)
                                                                              at android.support.v7.view.menu.b.a(Unknown Source)
                                                                              at android.support.v7.widget.d.a(Unknown Source)
                                                                              at android.support.v7.view.menu.h.d(Unknown Source)
                                                                              at android.support.v7.view.menu.h.a(Unknown Source)
                                                                              at android.support.v7.view.menu.h.h(Unknown Source)
                                                                              at android.support.v7.app.q.i(Unknown Source)
                                                                              at android.support.v7.app.q$1.run(Unknown Source)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:688)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:620)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
                                                                              at android.os.Handler.handleCallback(Handler.java:754)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:163)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6205)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                                                                           Caused by: java.lang.NoSuchFieldException: No field mItemData in class Landroid/support/v7/view/menu/ActionMenuItemView; (declaration of 'android.support.v7.view.menu.ActionMenuItemView' appears in /data/app/nu.com.example-1/base.apk)
                                                                              at java.lang.Class.getDeclaredField(Native Method)
                                                                              at com.afollestad.appthemeengine.inflation.a.i(Unknown Source) 
                                                                              at com.afollestad.appthemeengine.inflation.a.h(Unknown Source) 
                                                                              at com.afollestad.appthemeengine.inflation.a.setIcon(Unknown Source) 
                                                                              at android.support.v7.view.menu.ActionMenuItemView.a(Unknown Source) 
                                                                              at android.support.v7.widget.d.a(Unknown Source) 
                                                                              at android.support.v7.view.menu.b.a(Unknown Source) 
                                                                              at android.support.v7.widget.d.a(Unknown Source) 
                                                                              at android.support.v7.widget.d.a(Unknown Source) 
                                                                              at android.support.v7.view.menu.h.j(Unknown Source) 
                                                                              at android.support.v7.view.menu.b.a(Unknown Source) 
                                                                              at android.support.v7.widget.d.a(Unknown Source) 
                                                                              at android.support.v7.view.menu.h.d(Unknown Source) 
                                                                              at android.support.v7.view.menu.h.a(Unknown Source) 
                                                                              at android.support.v7.view.menu.h.h(Unknown Source) 
                                                                              at android.support.v7.app.q.i(Unknown Source) 
                                                                              at android.support.v7.app.q$1.run(Unknown Source) 
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876) 
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:688) 
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:620) 
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862) 
                                                                              at android.os.Handler.handleCallback(Handler.java:754) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                              at android.os.Looper.loop(Looper.java:163) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6205) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
``
```

**Comment by garretyoder** [comment]
afollestad, app-theme-engine's developer took the repo down for the project when he discontinued it. Many apps still depend on it, so I kept my fork up as a mirror. However, I recommend using my own Colorful library as a better alternative that is not out of support. https://github.com/garretyoder/Colorful
